import '@ant-design/v5-patch-for-react-19';

import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
// import 'antd/dist/reset.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { ConfigProvider } from 'antd';

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ConfigProvider theme={{token:{fontSize: 16}}}>
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AntdRegistry>
          {children}
        </AntdRegistry>
        <ToastContainer />
      </body>
    </html>
    </ConfigProvider>
  );
}
